config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "pages#index"
  
  resources :curses

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)

  if user.admin?
    can :update
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :content
   
end

app/models/content.rb
class Content < ApplicationRecord

belongs_to :curse
has_many :comments, dependent: :destroy 

 
end

app/models/curse.rb
class Curse < ApplicationRecord

# Associetion for Curse

has_many :enrollments
has_many :users, through: :enrollments
has_many :contents

end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :curse
  belongs_to :user
  
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :curse
end

app/models/user.rb
class User < ApplicationRecord

  # Association for User Model
  has_many :enrollments
  has_many :curses, through: :enrollments 
  has_one_attached :avatar_user
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



# Define show dashbaord teacher stats

  scope :teacher_total, -> { where teacher: 'true' }
  scope :student_total, -> { where student: 'true' }



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

 before_action :authenticate_user!
 before_action :configure_permitted_parameters, if: :devise_controller?
# layout
layout :layout_resource

# private

helper :all

private

def layout_resource

    if user_signed_in? == true
    "application"
    else 
     "login"
    end
    

end


def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:fname, :lname])
    devise_parameter_sanitizer.permit(:account_update, keys:  [:fname, :lname, :birthday, :avatar_user])
end

end

app/controllers/curses_controller.rb
class CursesController < ApplicationController


    def index
        @title = t('curses.title')
        @curses = Curse.all
      
    end

end

app/controllers/messager_controller.rb
class MessagerController < ApplicationController

  before_action :set_messager, only: [:show, :edit, :update, :destroy]

  def index

    @messager = current_user.messager

  end

  def new
    @messager = Messager.new
  end

  def create
    @messager =  Messager.new(messager_params)
    
    respond_to do |format|
      if @messager.save
        format.html { redirect_to @messager, notice: 'Mensagem enviado com sucesso!' }
        format.json { render :show, status: :created, location: @messager }
      else
        format.html { render :new }
        format.json { render json: @messager.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    #code
  end

  def edit
    #code
  end

  def update
    #code
  end

  def destroy

    @messager.destroy
    respond_to do |format|
      format.html {redirect_to messager_path, notice: "A mensagem foi apagado com sucesso!"}
      format.json { head :no_content  }
    end

  end

  private

  def set_messager
    @messager = Messager.find_by(params[:id])
  end

  def messager_params
    params.require(:messager).permit(:subject, :body, :user_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def index

       @title = t('title_dashboard') + ' ' + t('system_name')
         

    end


    private

    def set_pages
        
    end
    
    

end

app/helpers/application_helper.rb
module ApplicationHelper
   
require 'digest/md5'


# Define full name the users
 def full_name
     current_user.fname + ' ' +  current_user.lname
 end

# To define user type

 def user_type
    current_user.admin ? t('admin') : 
    current_user.teacher ? t('teacher') :
    current_user.student ? t('student') : ''
 end

 
 # User Avatar and images

 def user_avatar(user_photo, user_size)


hash = Digest::MD5.hexdigest(user_photo.email.downcase)
gravatar = "https://www.gravatar.com/avatar/#{hash}?s=#{user_size}&d=robohash"

  if current_user.avatar_user.attached? == false
    image_tag(gravatar, class: "app-sidebar__user-avatar")
  else
    image_tag(user_photo.avatar_user.variant(resize_to_limit: [user_size, user_size]), class: "app-sidebar__user-avatar")
  end
    
end
 

 # Define time for welcome

def welcome_time(time_here)
    
    case time_here.to_i

    when 0..11

       t('morning')
    
    when 12..18
    
       t('afternoon')
    
    when 18..23
       
       t("night")
      
    else
       
       "Hello!"
    end
end


end

app/helpers/curses_helper.rb
module CursesHelper
end

app/helpers/pages_helper.rb
module PagesHelper

    
def dashboard_user(user_dash)

 
  if user_dash.admin == true
    render "pages/director" 
  elsif user_dash.teacher == true
    render "pages/teacher"
  elsif user_dash.student == true
    render "pages/student"
  else
    
  end
 
end



end

app/views/curses/index.html.erb
<%= content_for :title do @title end %>

<div>
  <h1><i class="fa fa-search"></i> <%= yield :title %></h1>
  <p>A free and open source Bootstrap 4 admin template</p>
</div>
<ul class="app-breadcrumb breadcrumb">
  <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
  <li class="breadcrumb-item"><a href="<%= root_path %>">Dashboard</a></li>
  <li class="breadcrumb-item">Curses</a></li>
</ul>
</div>
 
 
 
 <div id="curse_data" data-curse="<%= @curses.to_json %>" ></div>

 <div id="component">
 lorem ipsom dolor sit amet, consect
 </div>
 


 <%= javascript_pack_tag("app") %>

app/views/curses/list.html.erb
<%= content_for(:title, "Meus cursos") %>
<header class="page-header">
            <div class="container-fluid">
              <h2 class="no-margin-bottom"><%= content_for(:title) %></h2>
            </div>
          </header>
<%= render "layouts/brandcrumb" %>
<p></p>
<div class="container">

  <div class="row">


<% @curses.each do |curses| %>

    <div class="col">
      <div class="card" style="width: 18rem;">
         <%= image_tag(curses.picture_url(:card)) %>

       <div class="card-body">
         <h5 class="card-title"> <%= fa_icon("leanpub") %> <%= curses.title %></h5>
         <p class="card-text"><%= curses.descricao %></p>
      
         <%= link_to "Assistir as Aulas", curse_home_path(curses), class: 'btn btn-outline-secondary btn-block' %>
       </div>
     </div>

    </div>

 <% end %>



  </div>






 </div>

app/views/layouts/_navtop.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">

  <%= link_to 'Pro Edu', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">

      <%= link_to '<i class="fa fa-fw fa-dashboard"></i><span class="nav-link-text"> Painel Principal</span>'.html_safe, root_path, class: 'nav-link' %>

      </li>
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Meu(s) Curso(s)">
           <%= link_to '<i class="fa fa-fw fa-graduation-cap"></i><span class="nav-link-text"> Meu Treinamento</span>'.html_safe, root_path, class: 'nav-link' %>
      </li>

      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tables">
        <%= link_to '<i class="fa fa-fw fa-list-alt "></i><span class="nav-link-text"> Conteúdo</span>'.html_safe, root_path, class: 'nav-link' %>

      </li>
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tables">
        <%= link_to '<i class="fa fa-fw fa-certificate"></i><span class="nav-link-text"> Certificado</span>'.html_safe, root_path, class: 'nav-link' %>

      </li>
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Components">
        <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseComponents" data-parent="#exampleAccordion">
          <i class="fa fa-fw fa-wrench"></i>
          <span class="nav-link-text">Components</span>
        </a>
        <ul class="sidenav-second-level collapse" id="collapseComponents">
          <li>
            <a href="navbar.html">Navbar</a>
          </li>
          <li>
            <a href="cards.html">Cards</a>
          </li>
        </ul>
      </li>
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Example Pages">
        <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseExamplePages" data-parent="#exampleAccordion">
          <i class="fa fa-fw fa-file"></i>
          <span class="nav-link-text">Example Pages</span>
        </a>
        <ul class="sidenav-second-level collapse" id="collapseExamplePages">
          <li>
            <a href="login.html">Login Page</a>
          </li>
          <li>
            <a href="register.html">Registration Page</a>
          </li>
          <li>
            <a href="forgot-password.html">Forgot Password Page</a>
          </li>
          <li>
            <a href="blank.html">Blank Page</a>
          </li>
        </ul>
      </li>
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Menu Levels">
        <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMulti" data-parent="#exampleAccordion">
          <i class="fa fa-fw fa-user"></i>
          <span class="nav-link-text">Meu Perfil</span>
        </a>
        <ul class="sidenav-second-level collapse" id="collapseMulti">
          <li>
            <%= link_to 'Editar', edit_user_registration_path %>
          </li>
          <li>
            <a href="#">Second Level Item</a>
          </li>
          <li>
            <a href="#">Second Level Item</a>
          </li>
          <li>
            <a class="nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMulti2">Third Level</a>
            <ul class="sidenav-third-level collapse" id="collapseMulti2">
              <li>
                <a href="#">Third Level Item</a>
              </li>
              <li>
                <a href="#">Third Level Item</a>
              </li>
              <li>
                <a href="#">Third Level Item</a>
              </li>
            </ul>
          </li>
        </ul>
      </li>
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Link">
        <a class="nav-link" href="#">
          <i class="fa fa-fw fa-link"></i>
          <span class="nav-link-text">Link</span>
        </a>
      </li>
    </ul>
    <ul class="navbar-nav sidenav-toggler">
      <li class="nav-item">
        <a class="nav-link text-center" id="sidenavToggler">
          <i class="fa fa-fw fa-angle-left"></i>
        </a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle mr-lg-2" id="messagesDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-fw fa-envelope"></i>
          <span class="d-lg-none">Messages
            <span class="badge badge-pill badge-primary">12 New</span>
          </span>
          <span class="indicator text-primary d-none d-lg-block">
            <i class="fa fa-fw fa-circle"></i>
          </span>
        </a>
        <div class="dropdown-menu" aria-labelledby="messagesDropdown">
          <h6 class="dropdown-header">New Messages:</h6>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">
            <strong>David Miller</strong>
            <span class="small float-right text-muted">11:21 AM</span>
            <div class="dropdown-message small">Hey there! This new version of SB Admin is pretty awesome! These messages clip off when they reach the end of the box so they don't overflow over to the sides!</div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">
            <strong>Jane Smith</strong>
            <span class="small float-right text-muted">11:21 AM</span>
            <div class="dropdown-message small">I was wondering if you could meet for an appointment at 3:00 instead of 4:00. Thanks!</div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">
            <strong>John Doe</strong>
            <span class="small float-right text-muted">11:21 AM</span>
            <div class="dropdown-message small">I've sent the final files over to you for review. When you're able to sign off of them let me know and we can discuss distribution.</div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item small" href="#">View all messages</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle mr-lg-2" id="alertsDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-fw fa-bell"></i>
          <span class="d-lg-none">Alerts
            <span class="badge badge-pill badge-warning">6 New</span>
          </span>
          <span class="indicator text-warning d-none d-lg-block">
            <i class="fa fa-fw fa-circle"></i>
          </span>
        </a>
        <div class="dropdown-menu" aria-labelledby="alertsDropdown">
          <h6 class="dropdown-header">New Alerts:</h6>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">
            <span class="text-success">
              <strong>
                <i class="fa fa-long-arrow-up fa-fw"></i>Status Update</strong>
            </span>
            <span class="small float-right text-muted">11:21 AM</span>
            <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">
            <span class="text-danger">
              <strong>
                <i class="fa fa-long-arrow-down fa-fw"></i>Status Update</strong>
            </span>
            <span class="small float-right text-muted">11:21 AM</span>
            <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">
            <span class="text-success">
              <strong>
                <i class="fa fa-long-arrow-up fa-fw"></i>Status Update</strong>
            </span>
            <span class="small float-right text-muted">11:21 AM</span>
            <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item small" href="#">View all alerts</a>
        </div>
      </li>
      <li class="nav-item">
        <form class="form-inline my-2 my-lg-0 mr-lg-2">
          <div class="input-group">
            <input class="form-control" type="text" placeholder="Search for...">
            <span class="input-group-btn">
              <button class="btn btn-primary" type="button">
                <i class="fa fa-search"></i>
              </button>
            </span>
          </div>
        </form>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
          <i class="fa fa-fw fa-sign-out"></i>Sair</a>
      </li>
    </ul>
  </div>
</nav>


<!-- Logout Modal-->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Você realmente deseja sair?</h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">Clique "Sair" abaixo se você realmente deseja sair da plataforma.</div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
       <%= link_to 'Sair', destroy_user_session_path, method: :delete, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navtop_admin.html.erb
<!-- Main Navbar-->
<header class="header">
<nav class="navbar">
<!-- Search Box-->
<div class="search-box">
<button class="dismiss"><i class="icon-close"></i></button>
<form id="searchForm" action="#" role="search">
<input type="search" placeholder="What are you looking for..." class="form-control">
</form>
</div>
<div class="container-fluid">
<div class="navbar-holder d-flex align-items-center justify-content-between">
<!-- Navbar Header-->
<div class="navbar-header">
<!-- Navbar Brand -->
<%= link_to "<div class='brand-text brand-big'><span>Pro </span><strong>EDU</strong></div>
<div class='brand-text brand-small'><strong>PE</strong></div>".html_safe, root_path, class: 'navbar-brand' %>

<!-- Toggle Button--><a id="toggle-btn" href="#" class="menu-btn active"><span></span><span></span><span></span></a>
</div>
<!-- Navbar Menu -->
<ul class="nav-menu list-unstyled d-flex flex-md-row align-items-md-center">
<!-- Search-->
<li class="nav-item d-flex align-items-center"><a id="search" href="#"><i class="icon-search"></i></a></li>
<!-- Notifications-->

  <!-- Messages                        -->

  <li class="nav-item dropdown">
  <!-- <a id="messages" rel="nofollow" data-target="#" href="#" data-toggle="dropdown" aria-haspopup="true"
      aria-expanded="false" class="nav-link">
      <i class="fa fa-envelope-o"></i>
        <span class="badge bg-red"><%= messager_count %></span></a>
    <ul aria-labelledby="notifications" class="dropdown-menu">
  <% if @messager == blank? %>
  <% else %>
      <% Messager.take(3).each do |messager| %>
      <li><a rel="nofollow" href="#" class="dropdown-item d-flex">
        <div class="msg-profile"> <%= image_tag(gravatar(messager.user.email, 40),
        class:'img-fluid rounded-circle' ) %>
         </div>
        <div class="msg-body">
          <h3 class="h5"><%= messager.user.name_with_initial %></h3><span>Enviou mensagem...</span>
        </div></a></li>
        <% end %>
<% end %>
        <li>
 <%= link_to '<strong>Todas as mensagens</strong>'.html_safe, messagers_path, class: 'dropdown-item all-notifications text-center' %>

     </li>
          </ul> -->
        </li>
        <!-- Logout    -->
        <li class="nav-item">

          <%= link_to "Logout<i class='fa fa-sign-out'></i>".html_safe, destroy_user_session_path, method: :delete, class: 'nav-link logout'  %>

        </li>
      </ul>
    </div>
  </div>
</nav>
</header>
<div class="page-content d-flex align-items-stretch">
<!-- Side Navbar -->
<nav class="side-navbar">
  <!-- Sidebar Header-->
  <div class="sidebar-header d-flex align-items-center">
    <div class="avatar">
      <%= image_tag(gravatar(current_user.email,'65'), class: 'img-fluid rounded-circle') %>
    </div>
    <div class="title">
      <h1 class="h4"><%= current_user.name.capitalize + ' ' + current_user.lastname.capitalize %></h1>
      <p>Administração</p>
    </div>
  </div>
  <!-- Sidebar Navidation Menus--><span class="heading">Main</span>
  <ul class="list-unstyled">
    <li class="<%= active_for(path: "/") %>" > <%= link_to '<i class="icon-home"></i>Home </a>'.html_safe , root_path %> </li>

    <li class="<%= active_for(controller: "curses") %>" ><a href="#cursosdropdownDropdown" aria-expanded="false" data-toggle="collapse">
      <i class="icon-interface-windows"></i> Cursos </a>
      <ul id="cursosdropdownDropdown" class="collapse list-unstyled ">
        <li> <%= link_to fa_icon('plus-circle', text: 'Criar Curso'), new_curse_path %></li>
        <li> <%= link_to fa_icon('list-alt', text: 'Gerenciar Curso(s)'), curses_path %></li>
      </ul>
    </li>

    <li class="<%= active_for(controller: "contents") %>" ><a
  href="#licaodropdownDropdown"  aria-expanded="false" data-toggle="collapse">
      <%= fa_icon('folder-open', text: 'Lição') %> </a>
      <ul id="licaodropdownDropdown" class="collapse list-unstyled ">
        <li> <%= link_to fa_icon('plus-circle', text: 'Criar Lição'), new_content_path %></li>
        <li> <%= link_to fa_icon('list-alt', text: 'Gerenciar Lição(es)'), contents_path %></li>
      </ul>
    </li>

    <li class="<%= active_for(controller: "categories") %>" ><a href="#categoriadropdownDropdown" 
    aria-expanded="false" data-toggle="collapse">
      <i class="icon-list-1"></i> Categoria </a> </a>
      <ul id="categoriadropdownDropdown" class="collapse list-unstyled ">
        <li> <%= link_to fa_icon('plus-circle', text: 'Criar Categoria'), new_category_path %></li>
        <li> <%= link_to fa_icon('list-alt', text: 'Lista Categoria(s)'), categories_path %></li>
      </ul>
    </li>
    <li> <%= link_to fa_icon('envelope', text: 'Mensagem'), messagers_path %></li>

    <li> <%= link_to fa_icon('user', text: 'Usuários'), users_path %></li>


</nav>

app/views/messager/_devisemessager.html.erb
<% if notice %>
	<div class='alert alert-success'>
		<%= notice %>
	</div>
<% end %>

<% if alert %>
	<div class='alert alert-danger'>
		<%= alert %>
	</div>
<% end %>

app/views/pages/index.html.erb
<%= content_for :title do @title end %>


<%= dashboard_user(current_user) %>

 </div>

app/views/partials/_sidebar.html.erb
<div class="app-sidebar__overlay" data-toggle="sidebar"></div>
    <aside class="app-sidebar">
      <div class="app-sidebar__user">   <%= user_avatar(current_user, 48) %>
        <div>
          <p class="app-sidebar__user-name"><%= full_name %></p>
          <p class="app-sidebar__user-designation"><%= welcome_time(Time.now.strftime("%H")) %>, <%= user_type %></p>
        </div>
      </div>
      <ul class="app-menu">
       <%=
       
       if current_user.admin == true 
         render("partials/sidebar/director") 
        elsif current_user.teacher == true 
        render("partials/sidebar/teacher")
        elsif current_user.student == true
        render("partials/sidebar/student")
       end
       %>
       
      </ul>
    </aside>

app/views/partials/sidebar/_student.html.erb
 <li><%= link_to root_path, class: "app-menu__item #{controller_name == "pages" ? "active" : ""}" do %>
 <i class="app-menu__icon fa fa-dashboard"></i><span
       class="app-menu__label"><%= t('sidebar.dashboard') %></span>
    <% end %>
 </li>

  <li><%= link_to curses_path, class: "app-menu__item #{controller_name == "curses" ? "active" : ""}" do %>
 <i class="app-menu__icon fa fa-search"></i><span
       class="app-menu__label"><%=  t('sidebar.curse').pluralize(User.count) %></span>
    <% end %>
 </li>
 
 <li><%= link_to curses_path, class: "app-menu__item #{controller_name == "" ? "active" : ""}" do %>
 <i class="app-menu__icon fa fa-graduation-cap"></i><span
       class="app-menu__label"><%=  t('sidebar.curse').pluralize(User.count) %></span>
    <% end %>
 </li>
 
 <li class="treeview"><a class="app-menu__item" href="#" data-toggle="treeview"><i
       class="app-menu__icon fa fa-laptop"></i><span class="app-menu__label">UI Elements</span><i
       class="treeview-indicator fa fa-angle-right"></i></a>
   <ul class="treeview-menu">
     <li><a class="treeview-item" href="bootstrap-components.html"><i class="icon fa fa-circle-o"></i> Bootstrap
         Elements</a></li>
     <li><a class="treeview-item" href="https://fontawesome.com/v4.7.0/icons/" target="_blank" rel="noopener"><i
           class="icon fa fa-circle-o"></i> Font Icons</a></li>
     <li><a class="treeview-item" href="ui-cards.html"><i class="icon fa fa-circle-o"></i> Cards</a></li>
     <li><a class="treeview-item" href="widgets.html"><i class="icon fa fa-circle-o"></i> Widgets</a></li>
   </ul>
 </li>
 <%# <li><a class="app-menu__item" href="charts.html"><i class="app-menu__icon fa fa-pie-chart"></i><span
       class="app-menu__label">Charts</span></a></li>
 <li class="treeview"><a class="app-menu__item" href="#" data-toggle="treeview"><i
       class="app-menu__icon fa fa-edit"></i><span class="app-menu__label">Forms</span><i
       class="treeview-indicator fa fa-angle-right"></i></a>
   <ul class="treeview-menu">
     <li><a class="treeview-item" href="form-components.html"><i class="icon fa fa-circle-o"></i> Form Components</a>
     </li>
     <li><a class="treeview-item" href="form-custom.html"><i class="icon fa fa-circle-o"></i> Custom Components</a></li>
     <li><a class="treeview-item" href="form-samples.html"><i class="icon fa fa-circle-o"></i> Form Samples</a></li>
     <li><a class="treeview-item" href="form-notifications.html"><i class="icon fa fa-circle-o"></i> Form
         Notifications</a></li>
   </ul>
 </li> %>
 <%# <li class="treeview"><a class="app-menu__item" href="#" data-toggle="treeview"><i
       class="app-menu__icon fa fa-th-list"></i><span class="app-menu__label">Tables</span><i
       class="treeview-indicator fa fa-angle-right"></i></a>
   <ul class="treeview-menu">
     <li><a class="treeview-item" href="table-basic.html"><i class="icon fa fa-circle-o"></i> Basic Tables</a></li>
     <li><a class="treeview-item" href="table-data-table.html"><i class="icon fa fa-circle-o"></i> Data Tables</a></li>
   </ul>
 </li> %>
 <%# <li class="treeview"><a class="app-menu__item" href="#" data-toggle="treeview"><i class="app-menu__icon fa fa-file-text"></i><span class="app-menu__label">Pages</span><i class="treeview-indicator fa fa-angle-right"></i></a>
          <ul class="treeview-menu">
            <li><a class="treeview-item" href="blank-page.html"><i class="icon fa fa-circle-o"></i> Blank Page</a></li>
            <li><a class="treeview-item" href="page-login.html"><i class="icon fa fa-circle-o"></i> Login Page</a></li>
            <li><a class="treeview-item" href="page-lockscreen.html"><i class="icon fa fa-circle-o"></i> Lockscreen Page</a></li>
            <li><a class="treeview-item" href="page-user.html"><i class="icon fa fa-circle-o"></i> User Page</a></li>
            <li><a class="treeview-item" href="page-invoice.html"><i class="icon fa fa-circle-o"></i> Invoice Page</a></li>
            <li><a class="treeview-item" href="page-calendar.html"><i class="icon fa fa-circle-o"></i> Calendar Page</a></li>
            <li><a class="treeview-item" href="page-mailbox.html"><i class="icon fa fa-circle-o"></i> Mailbox</a></li>
            <li><a class="treeview-item" href="page-error.html"><i class="icon fa fa-circle-o"></i> Error Page</a></li>
          </ul>
        </li> %>
 <li><a class="app-menu__item" href="docs.html"><i class="app-menu__icon fas fa-file-code-o"></i><span
       class="app-menu__label">Docs</span></a></li>